apiVersion: v1
kind: Secret
metadata:
  name: sensor-storage-secrets
  namespace: sensor-storage
type: Opaque
stringData:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  AZURE_STORAGE_ACCOUNT: "your_storage_account"
  AZURE_STORAGE_KEY: "your_storage_key"